In [2]:
import gzip
import pandas as pd
import requests
from io import BytesIO

def load_data_from_github(url):
    response = requests.get(url)
    compressed_file = BytesIO(response.content)
    with gzip.open(compressed_file, 'rt') as file:
        data = pd.read_csv(file, sep='\t', header=None)
    return data

url = 'https://raw.githubusercontent.com/laiguokun/multivariate-time-series-data/master/electricity/electricity.txt.gz'
data = load_data_from_github(url)

In [5]:
data.head(15)

                                                    0
0   14.000000,69.000000,234.000000,415.000000,215....
1   18.000000,92.000000,312.000000,556.000000,292....
2   21.000000,96.000000,312.000000,560.000000,272....
3   20.000000,92.000000,312.000000,443.000000,213....
4   22.000000,91.000000,312.000000,346.000000,190....
5   20.000000,92.000000,187.000000,340.000000,178....
6   20.000000,91.000000,138.000000,376.000000,199....
7   20.000000,92.000000,8.000000,361.000000,187.00...
8   13.000000,91.000000,7.000000,259.000000,144.00...
9   11.000000,96.000000,8.000000,402.000000,172.00...
10  64.000000,113.000000,13.000000,446.000000,191....
11  53.000000,142.000000,11.000000,551.000000,200....
12  26.000000,158.000000,11.000000,532.000000,236....
13  10.000000,147.000000,13.000000,364.000000,187....
14  28.000000,122.000000,17.000000,294.000000,197....